# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/shared/blockchain.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eprotos/shared/blockchain.proto\x12\x1dsh.coherent.blockchain.shared*^\n\nBlockchain\x12\x0c\n\x08\x45THEREUM\x10\x00\x12\x0c\n\x08OPTIMISM\x10\x01\x12\x0b\n\x07POLYGON\x10\x02\x12\r\n\tAVALANCHE\x10\x03\x12\x0c\n\x08\x41RBITRUM\x10\x04\x12\n\n\x06GOERLI\x10\x05\x42\x38Z6github.com/coherent-api/data-platform/protos/go/sharedb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.shared.blockchain_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z6github.com/coherent-api/data-platform/protos/go/shared'
  _BLOCKCHAIN._serialized_start=65
  _BLOCKCHAIN._serialized_end=159
# @@protoc_insertion_point(module_scope)
