version: "3.9"
services:
  gcs:
    image: "fsouza/fake-gcs-server"
    ports:
      - "4443:4443"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - '5432:5432'