// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: protos/evm/node_client/evm_client.proto

package node_client

import (
	shared "github.com/coherent-api/contract-poller/protos/go/protos/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetContractResponse_AddressType int32

const (
	GetContractResponse_USER     GetContractResponse_AddressType = 0
	GetContractResponse_CONTRACT GetContractResponse_AddressType = 1
	GetContractResponse_ERC20    GetContractResponse_AddressType = 2
	GetContractResponse_ERC721   GetContractResponse_AddressType = 3
	GetContractResponse_ERC1155  GetContractResponse_AddressType = 4
)

// Enum value maps for GetContractResponse_AddressType.
var (
	GetContractResponse_AddressType_name = map[int32]string{
		0: "USER",
		1: "CONTRACT",
		2: "ERC20",
		3: "ERC721",
		4: "ERC1155",
	}
	GetContractResponse_AddressType_value = map[string]int32{
		"USER":     0,
		"CONTRACT": 1,
		"ERC20":    2,
		"ERC721":   3,
		"ERC1155":  4,
	}
)

func (x GetContractResponse_AddressType) Enum() *GetContractResponse_AddressType {
	p := new(GetContractResponse_AddressType)
	*p = x
	return p
}

func (x GetContractResponse_AddressType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetContractResponse_AddressType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_evm_node_client_evm_client_proto_enumTypes[0].Descriptor()
}

func (GetContractResponse_AddressType) Type() protoreflect.EnumType {
	return &file_protos_evm_node_client_evm_client_proto_enumTypes[0]
}

func (x GetContractResponse_AddressType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetContractResponse_AddressType.Descriptor instead.
func (GetContractResponse_AddressType) EnumDescriptor() ([]byte, []int) {
	return file_protos_evm_node_client_evm_client_proto_rawDescGZIP(), []int{1, 0}
}

type GetContractRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address    string            `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Blockchain shared.Blockchain `protobuf:"varint,2,opt,name=blockchain,proto3,enum=Blockchain" json:"blockchain,omitempty"`
}

func (x *GetContractRequest) Reset() {
	*x = GetContractRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_evm_node_client_evm_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractRequest) ProtoMessage() {}

func (x *GetContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_evm_node_client_evm_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractRequest.ProtoReflect.Descriptor instead.
func (*GetContractRequest) Descriptor() ([]byte, []int) {
	return file_protos_evm_node_client_evm_client_proto_rawDescGZIP(), []int{0}
}

func (x *GetContractRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetContractRequest) GetBlockchain() shared.Blockchain {
	if x != nil {
		return x.Blockchain
	}
	return shared.Blockchain(0)
}

type GetContractResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  string                          `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Type     GetContractResponse_AddressType `protobuf:"varint,2,opt,name=type,proto3,enum=sh.coherent.evm_client.shared.GetContractResponse_AddressType" json:"type,omitempty"`
	Name     string                          `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Symbol   string                          `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals int32                           `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Bytecode []byte                          `protobuf:"bytes,6,opt,name=bytecode,proto3" json:"bytecode,omitempty"`
}

func (x *GetContractResponse) Reset() {
	*x = GetContractResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_evm_node_client_evm_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractResponse) ProtoMessage() {}

func (x *GetContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_evm_node_client_evm_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractResponse.ProtoReflect.Descriptor instead.
func (*GetContractResponse) Descriptor() ([]byte, []int) {
	return file_protos_evm_node_client_evm_client_proto_rawDescGZIP(), []int{1}
}

func (x *GetContractResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetContractResponse) GetType() GetContractResponse_AddressType {
	if x != nil {
		return x.Type
	}
	return GetContractResponse_USER
}

func (x *GetContractResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetContractResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetContractResponse) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *GetContractResponse) GetBytecode() []byte {
	if x != nil {
		return x.Bytecode
	}
	return nil
}

var File_protos_evm_node_client_evm_client_proto protoreflect.FileDescriptor

var file_protos_evm_node_client_evm_client_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65, 0x76, 0x6d, 0x2f, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x65, 0x76, 0x6d, 0x5f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x73, 0x68, 0x2e, 0x63, 0x6f,
	0x68, 0x65, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x65, 0x76, 0x6d, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x1a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2b, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x22, 0xb2, 0x02, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x52, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3e, 0x2e, 0x73, 0x68, 0x2e, 0x63, 0x6f, 0x68, 0x65, 0x72,
	0x65, 0x6e, 0x74, 0x2e, 0x65, 0x76, 0x6d, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d,
	0x61, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d,
	0x61, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x79, 0x74, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x62, 0x79, 0x74, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x22,
	0x49, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08,
	0x0a, 0x04, 0x55, 0x53, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f, 0x4e, 0x54,
	0x52, 0x41, 0x43, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x43, 0x32, 0x30, 0x10,
	0x02, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x52, 0x43, 0x37, 0x32, 0x31, 0x10, 0x03, 0x12, 0x0b, 0x0a,
	0x07, 0x45, 0x52, 0x43, 0x31, 0x31, 0x35, 0x35, 0x10, 0x04, 0x32, 0x83, 0x01, 0x0a, 0x09, 0x45,
	0x56, 0x4d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x76, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x31, 0x2e, 0x73, 0x68, 0x2e, 0x63, 0x6f, 0x68,
	0x65, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x65, 0x76, 0x6d, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x73, 0x68, 0x2e,
	0x63, 0x6f, 0x68, 0x65, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x65, 0x76, 0x6d, 0x5f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x6f, 0x68, 0x65, 0x72, 0x65, 0x6e, 0x74, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65, 0x76, 0x6d,
	0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_evm_node_client_evm_client_proto_rawDescOnce sync.Once
	file_protos_evm_node_client_evm_client_proto_rawDescData = file_protos_evm_node_client_evm_client_proto_rawDesc
)

func file_protos_evm_node_client_evm_client_proto_rawDescGZIP() []byte {
	file_protos_evm_node_client_evm_client_proto_rawDescOnce.Do(func() {
		file_protos_evm_node_client_evm_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_evm_node_client_evm_client_proto_rawDescData)
	})
	return file_protos_evm_node_client_evm_client_proto_rawDescData
}

var file_protos_evm_node_client_evm_client_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_evm_node_client_evm_client_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_evm_node_client_evm_client_proto_goTypes = []interface{}{
	(GetContractResponse_AddressType)(0), // 0: sh.coherent.evm_client.shared.GetContractResponse.AddressType
	(*GetContractRequest)(nil),           // 1: sh.coherent.evm_client.shared.GetContractRequest
	(*GetContractResponse)(nil),          // 2: sh.coherent.evm_client.shared.GetContractResponse
	(shared.Blockchain)(0),               // 3: Blockchain
}
var file_protos_evm_node_client_evm_client_proto_depIdxs = []int32{
	3, // 0: sh.coherent.evm_client.shared.GetContractRequest.blockchain:type_name -> Blockchain
	0, // 1: sh.coherent.evm_client.shared.GetContractResponse.type:type_name -> sh.coherent.evm_client.shared.GetContractResponse.AddressType
	1, // 2: sh.coherent.evm_client.shared.EVMClient.GetContract:input_type -> sh.coherent.evm_client.shared.GetContractRequest
	2, // 3: sh.coherent.evm_client.shared.EVMClient.GetContract:output_type -> sh.coherent.evm_client.shared.GetContractResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_evm_node_client_evm_client_proto_init() }
func file_protos_evm_node_client_evm_client_proto_init() {
	if File_protos_evm_node_client_evm_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_evm_node_client_evm_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetContractRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_evm_node_client_evm_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetContractResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_evm_node_client_evm_client_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_evm_node_client_evm_client_proto_goTypes,
		DependencyIndexes: file_protos_evm_node_client_evm_client_proto_depIdxs,
		EnumInfos:         file_protos_evm_node_client_evm_client_proto_enumTypes,
		MessageInfos:      file_protos_evm_node_client_evm_client_proto_msgTypes,
	}.Build()
	File_protos_evm_node_client_evm_client_proto = out.File
	file_protos_evm_node_client_evm_client_proto_rawDesc = nil
	file_protos_evm_node_client_evm_client_proto_goTypes = nil
	file_protos_evm_node_client_evm_client_proto_depIdxs = nil
}
