# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/evm/enriched/enriched.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"protos/evm/enriched/enriched.proto\x12#sh.coherent.blockchain.evm.enriched\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x01\n\x05\x42lock\x12\x12\n\nblock_hash\x18\x01 \x01(\t\x12\x14\n\x0c\x62lock_number\x18\x02 \x01(\x03\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x46\n\x0ctransactions\x18\x04 \x03(\x0b\x32\x30.sh.coherent.blockchain.evm.enriched.Transaction\"\x89\x02\n\x0bTransaction\x12K\n\x0f\x61ssets_received\x18\x01 \x03(\x0b\x32\x32.sh.coherent.blockchain.evm.enriched.AssetTransfer\x12G\n\x0b\x61ssets_sent\x18\x02 \x03(\x0b\x32\x32.sh.coherent.blockchain.evm.enriched.AssetTransfer\x12\x0c\n\x04\x66rom\x18\x03 \x01(\t\x12\x0b\n\x03gas\x18\x04 \x01(\t\x12\x11\n\tgas_price\x18\x05 \x01(\t\x12\x0c\n\x04hash\x18\x06 \x01(\t\x12\x0e\n\x06object\x18\x07 \x01(\t\x12\n\n\x02to\x18\x08 \x01(\t\x12\x0c\n\x04verb\x18\t \x01(\t\"\x98\x01\n\rAssetTransfer\x12\x15\n\rasset_address\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\t\x12\x12\n\nasset_name\x18\x03 \x01(\t\x12\x0c\n\x04\x66rom\x18\x04 \x01(\t\x12\n\n\x02to\x18\x05 \x01(\t\x12\x10\n\x08standard\x18\x06 \x01(\t\x12\x0e\n\x06symbol\x18\x07 \x01(\t\x12\x10\n\x08token_id\x18\x08 \x01(\tB>Z<github.com/coherent-api/data-platform/protos/go/evm/enrichedb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.evm.enriched.enriched_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z<github.com/coherent-api/data-platform/protos/go/evm/enriched'
  _BLOCK._serialized_start=109
  _BLOCK._serialized_end=277
  _TRANSACTION._serialized_start=280
  _TRANSACTION._serialized_end=545
  _ASSETTRANSFER._serialized_start=548
  _ASSETTRANSFER._serialized_end=700
# @@protoc_insertion_point(module_scope)
