// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// error is an autogenerated mock type for the error type
type error struct {
	mock.Mock
}

// Error provides a mock function with given fields:
func (_m *error) Error() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTnewError interface {
	mock.TestingT
	Cleanup(func())
}

// newError creates a new instance of error. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newError(t mockConstructorTestingTnewError) *error {
	mock := &error{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
