// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ContractPoller is an autogenerated mock type for the ContractPoller type
type ContractPoller struct {
	mock.Mock
}

// Start provides a mock function with given fields: ctx
func (_m *ContractPoller) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewContractPoller interface {
	mock.TestingT
	Cleanup(func())
}

// NewContractPoller creates a new instance of ContractPoller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewContractPoller(t mockConstructorTestingTNewContractPoller) *ContractPoller {
	mock := &ContractPoller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
