// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	constants "github.com/coherent-api/contract-poller/shared/constants"

	etherscan "github.com/nanmu42/etherscan-api"

	mock "github.com/stretchr/testify/mock"
)

// EvmClient is an autogenerated mock type for the EvmClient type
type EvmClient struct {
	mock.Mock
}

// ContractSource provides a mock function with given fields: ctx, contractAddress, blockchain
func (_m *EvmClient) ContractSource(ctx context.Context, contractAddress string, blockchain constants.Blockchain) (etherscan.ContractSource, error) {
	ret := _m.Called(ctx, contractAddress, blockchain)

	var r0 etherscan.ContractSource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, constants.Blockchain) (etherscan.ContractSource, error)); ok {
		return rf(ctx, contractAddress, blockchain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, constants.Blockchain) etherscan.ContractSource); ok {
		r0 = rf(ctx, contractAddress, blockchain)
	} else {
		r0 = ret.Get(0).(etherscan.ContractSource)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, constants.Blockchain) error); ok {
		r1 = rf(ctx, contractAddress, blockchain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetContractABI provides a mock function with given fields: ctx, contractAddress
func (_m *EvmClient) GetContractABI(ctx context.Context, contractAddress string) (string, error) {
	ret := _m.Called(ctx, contractAddress)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, contractAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, contractAddress)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, contractAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewEvmClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewEvmClient creates a new instance of EvmClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEvmClient(t mockConstructorTestingTNewEvmClient) *EvmClient {
	mock := &EvmClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
