// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Func is an autogenerated mock type for the Func type
type Func struct {
	mock.Mock
}

// Execute provides a mock function with given fields: attempt
func (_m *Func) Execute(attempt int) (bool, error) {
	ret := _m.Called(attempt)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(attempt)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(attempt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewFunc creates a new instance of Func. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFunc(t mockConstructorTestingTNewFunc) *Func {
	mock := &Func{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
